
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/forum
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.163.com
    username: htwx123qq@163.com
    password: JDaZXubxBGseN283
server:
  port: 8081
