
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/forum
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.163.com
    username: htwx123qq@163.com
    password: JDaZXubxBGseN283
  minio:
    endpoint: http://localhost:9000
    username: minioadmin
    password: minioadmin
  weather:
    key: b70c46e3b04e451493a009a3cb290926
server:
  port: 8081
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
